# -*- coding: utf-8 -*-
"""HackerRank_9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A8SF9RrwoqidJhwOcBhKuYpKsFI6esFb
"""

import math

def ninth():
  n = int(input("Enter the number you want to calculate the factorial of : "))
  print('\n')
  print('The first method to calculate the factorial is as follows : ')
  print('\n')
  print(math.factorial(n))
  print('\n')
  print('The second method is as follows : ')
  print('\n')
  a = 1
  for i in range(1,n+1):
    a = a*i
    print(a)

ninth()

