# -*- coding: utf-8 -*-
"""HackerRank_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D-4o25RDNLu5AfHGAr_AzH9m9FqMO_A0
"""

def first():
  i = int(input('Enter an integer value : '))
  d = float(input('Enter the float value : '))
  s = str(input('Enter the string value : '))

  print(i)
  print(d * 2)
  print(s)

first()

