# -*- coding: utf-8 -*-
"""HackerRank_10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q1uLIX9UxsDUZHAbS1DxZKpp2Ds7N_A7
"""

#importing libraries
import sys
import os
import random
import math
print('\n')
print('Libraries Imported.')
print('\n')

a = 79
bin_a = bin(a)
print(bin_a)
format(79, "08b")

def tenth():
  n = int(input('Enter the number : '))
  bin_n = format(n, "08b")
  print('\n')
  print(bin_n)
  print('\n')

  count = 0
  max_count = 0
  for i in bin_n:
    if i.startswith == 1:
      print(i)
      count += 1
    else:
      if count > max_count:
        max_count = count
      count = 0
  if count > max_count:
      max_count = count
  print (max_count)

tenth()

n = int(input())

max_one_count = 0
one_count = 0

while n != 0:
	factor = n // 2
	remainder = n - 2 * factor
	n = factor
	if remainder == 1:
		one_count += 1
		max_one_count = max(max_one_count, one_count)
	else:
		one_count = 0

print(max_one_count)

