# -*- coding: utf-8 -*-
"""HackerRank_3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SUo5-Yn2soJe2GgGoKWSp-TqBQZgI47b
"""

import math
import os
import random
import re
import sys

def third():
  a = int(input('Enter the number to see in which condition the input number lies : '))

  if a%2 == 1:
    print('Weird.')
  
  if a%2==0 in range(2,6):
    print('Not Weird.')
  
  if a%2==0 in range(6,40):
    print('Weird')

  if a > 20:
    print('Not Weird.')

third()

