# -*- coding: utf-8 -*-
"""HackerRank_6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IE0ekSafQ_zKoFpdr269t4vvBaATrlN9
"""

N = int(input())

evenlist = [] 
oddlist = []

for i in range(0,N): 
   string=input() 
   evenlist.clear() 
   oddlist.clear() 
   for item, char in enumerate(string): 
     if item % 2 == 0: 
       evenlist.append(char) 
     else: oddlist.append(char) 
   print(''.join(evenlist),''.join(oddlist))

print('')

