# -*- coding: utf-8 -*-
"""HackerRank_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zLlN5iCqMSVDWof-NbXsG8vEVKrgy3gF
"""

#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.
def solve():

  meal_cost = float(input())

  tip_percent = int(input())

  tax_percent = int(input())

  tip = meal_cost * tip_percent/100
  tax = meal_cost * tax_percent/100
  total_cost = meal_cost + tip + tax

  return total_cost

solve()

