# -*- coding: utf-8 -*-
"""HackerRank_7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yMdj9sVdJ8_0Z71MvOxvpVkvqmOBqSRH
"""

#defining the function
def seventh():
  n = list(map(int, input("Enter the list of numbers : ").rstrip().split( )))
  print('\n')
  print(n)
  print('\n')
  print(n[::-1])
seventh()

